[0m14:27:21.112735 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10274add0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1042c4a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1042cbed0>]}


============================== 14:27:21.119271 | bcf77f15-024a-404e-9b07-7cf4d798f6fc ==============================
[0m14:27:21.119271 [info ] [MainThread]: Running with dbt=1.5.4
[0m14:27:21.120065 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/zaeemathar/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m14:27:21.121051 [error] [MainThread]: Encountered an error:
1
[0m14:27:21.124623 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/zaeemathar/Projects/gcp_starter_pack_ecommerce/.venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zaeemathar/Projects/gcp_starter_pack_ecommerce/.venv/lib/python3.11/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zaeemathar/Projects/gcp_starter_pack_ecommerce/.venv/lib/python3.11/site-packages/dbt/cli/main.py", line 459, in init
    results = task.run()
              ^^^^^^^^^^
  File "/Users/zaeemathar/Projects/gcp_starter_pack_ecommerce/.venv/lib/python3.11/site-packages/dbt/task/init.py", line 287, in run
    sys.exit(1)
SystemExit: 1

[0m14:27:21.125641 [debug] [MainThread]: Command `dbt init` failed at 14:27:21.125465 after 0.05 seconds
[0m14:27:21.126046 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1042bc210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1042df890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100972150>]}
[0m14:27:21.126460 [debug] [MainThread]: Flushing usage events
[0m14:30:18.450077 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ee6790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ee52d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f070d0>]}


============================== 14:30:18.454740 | 787c068b-a2ee-4b46-85fa-8c2479888065 ==============================
[0m14:30:18.454740 [info ] [MainThread]: Running with dbt=1.6.0
[0m14:30:18.455551 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/zaeemathar/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init shopify_dbt', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:30:18.456765 [debug] [MainThread]: Starter project path: /Users/zaeemathar/Projects/gcp_starter_pack_ecommerce/.venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m14:30:18.464132 [info ] [MainThread]: 
Your new dbt project "shopify_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:30:18.464944 [info ] [MainThread]: Setting up your profile.
[0m14:32:33.691672 [info ] [MainThread]: Profile shopify_dbt written to /Users/zaeemathar/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:32:33.692901 [debug] [MainThread]: Command `dbt init` succeeded at 14:32:33.692666 after 135.26 seconds
[0m14:32:33.693597 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f130d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108f13e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049c4a10>]}
[0m14:32:33.694231 [debug] [MainThread]: Flushing usage events
